# Generated by Django 5.2.7 on 2026-10-05 21:26

import django.core.validators
import django.db.models.deletion
import wardrobe.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Garment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('image', models.ImageField(upload_to=wardrobe.models.garment_image_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])])),
                ('category', models.CharField(choices=[('top', 'Top'), ('bottom', 'Bottom'), ('dress', 'Dress'), ('outerwear', 'Outerwear'), ('shoes', 'Shoes'), ('accessory', 'Accessory'), ('other', 'Other')], default='other', max_length=30)),
                ('color', models.CharField(blank=True, max_length=100)),
                ('secondary_colors', models.JSONField(blank=True, default=list)),
                ('material', models.CharField(blank=True, max_length=100)),
                ('pattern', models.CharField(blank=True, max_length=100)),
                ('formality', models.CharField(choices=[('casual', 'Casual'), ('smart_casual', 'Smart casual'), ('formal', 'Formal'), ('sport', 'Sport'), ('other', 'Other')], default='casual', max_length=30)),
                ('season', models.CharField(blank=True, max_length=100)),
                ('weather_suitability', models.JSONField(blank=True, default=list)),
                ('description', models.TextField(blank=True)),
                ('ai_confidence', models.FloatField(blank=True, null=True)),
                ('ai_analyzed', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('available', 'Available'), ('unavailable', 'Unavailable'), ('archived', 'Archived')], default='available', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='garments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GarmentAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_response', models.JSONField(blank=True, default=dict)),
                ('model_name', models.CharField(blank=True, max_length=100)),
                ('analyzed_at', models.DateTimeField(auto_now=True)),
                ('garment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='wardrobe.garment')),
            ],
        ),
        migrations.AddIndex(
            model_name='garment',
            index=models.Index(fields=['user', 'status'], name='wardrobe_ga_user_id_7d3ebf_idx'),
        ),
        migrations.AddIndex(
            model_name='garment',
            index=models.Index(fields=['user', 'category'], name='wardrobe_ga_user_id_77cc47_idx'),
        ),
    ]
