# Generated by Django 5.2.7 on 2026-10-05 21:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wardrobe', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField()),
                ('city', models.CharField(max_length=100)),
                ('preferred_formality', models.CharField(default='casual', max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('generated', 'Generated'), ('failed', 'Failed')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-week_start'],
            },
        ),
        migrations.CreateModel(
            name='Outfit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('title', models.CharField(max_length=200)),
                ('explanation', models.TextField(blank=True)),
                ('temperature_min', models.FloatField(blank=True, null=True)),
                ('temperature_max', models.FloatField(blank=True, null=True)),
                ('weather_summary', models.CharField(blank=True, max_length=200)),
                ('generated_by_ai', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('weekly_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outfits', to='planner.weeklyplan')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='OutfitItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(default='item', max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('garment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outfit_items', to='wardrobe.garment')),
                ('outfit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='planner.outfit')),
            ],
            options={
                'ordering': ['order'],
                'constraints': [models.UniqueConstraint(fields=('outfit', 'garment'), name='unique_outfit_garment')],
            },
        ),
        migrations.AddConstraint(
            model_name='weeklyplan',
            constraint=models.UniqueConstraint(fields=('user', 'week_start'), name='unique_user_week'),
        ),
        migrations.AddConstraint(
            model_name='outfit',
            constraint=models.UniqueConstraint(fields=('weekly_plan', 'date'), name='unique_plan_outfit_date'),
        ),
    ]
